DogUin-Community/doguin

- src/main/java/com/sparta/doguin/domain/answer/entity/Answer.java
- src/main/java/com/sparta/doguin/domain/answer/enums/CommentType.java
- src/main/java/com/sparta/doguin/domain/question/entity/Question.java
- src/main/java/com/sparta/doguin/domain/question/enums/FirstCategory.java
- src/main/java/com/sparta/doguin/domain/question/enums/LastCategory.java
- src/main/java/com/sparta/doguin/domain/question/enums/QuestionStatus.java
- src/main/java/com/sparta/doguin/domain/question/enums/SecondCategory.java
> 질문, 답변 엔티티 추가

- src/main/java/com/sparta/doguin/domain/question/controller/QuestionController.java
- src/main/java/com/sparta/doguin/domain/question/dto/QuestionRequest.java
- src/main/java/com/sparta/doguin/domain/question/dto/QuestionResponse.java
- src/main/java/com/sparta/doguin/domain/question/entity/Question.java
- src/main/java/com/sparta/doguin/domain/question/enums/FirstCategory.java
- src/main/java/com/sparta/doguin/domain/question/enums/LastCategory.java
- src/main/java/com/sparta/doguin/domain/question/enums/QuestionStatus.java
- src/main/java/com/sparta/doguin/domain/question/enums/SecondCategory.java
- src/main/java/com/sparta/doguin/domain/question/repository/QuestionRepository.java
- src/main/java/com/sparta/doguin/domain/question/service/QuestionService.java
> feat. 질문 CRUD 구현

- build.gradle
- src/main/java/com/sparta/doguin/domain/common/exception/GlobalExceptionHandler.java
- src/main/java/com/sparta/doguin/domain/common/exception/ValidatorException.java
- src/main/java/com/sparta/doguin/domain/common/response/ApiResponseOutsourcingEnum.java
- src/main/java/com/sparta/doguin/domain/outsourcing/controller/OutsourcingController.java
- src/main/java/com/sparta/doguin/domain/outsourcing/model/OutsourctingDto.java
- src/main/java/com/sparta/doguin/domain/outsourcing/service/OutsourcingService.java
- src/main/java/com/sparta/doguin/domain/outsourcing/service/OutsourcingServiceImpl.java
- src/main/java/com/sparta/doguin/domain/outsourcing/validate/OutsourcingValidator.java
> refactor. 외주 CRUD 수정 및 이름 변경

- src/main/java/com/sparta/doguin/domain/answer/AnswerType.java
- src/main/java/com/sparta/doguin/domain/answer/controller/AnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/ApplyAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/BulletinAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/InquiryAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/NoticeAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/QuestionAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/dto/AnswerRequest.java
- src/main/java/com/sparta/doguin/domain/answer/dto/AnswerResponse.java
- src/main/java/com/sparta/doguin/domain/answer/entity/Answer.java
- src/main/java/com/sparta/doguin/domain/answer/repository/AnswerRepository.java
- src/main/java/com/sparta/doguin/domain/answer/service/AnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/ApplyAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/BulletinAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/InquiryAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/NoticeAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/QuestionAnswerService.java
답변(자유 게시판, 대답변, 1:1문의, 질문) 기본 CRUD 구현
> feat. 답변(자유 게시판, 대답변, 1:1문의, 질문) 기본 CRUD 구현

- src/main/java/com/sparta/doguin/domain/common/response/ApiResponseQuestionEnum.java
- src/main/java/com/sparta/doguin/domain/question/controller/QuestionController.java
- src/main/java/com/sparta/doguin/domain/question/service/QuestionService.java
> refact. 질문(Question) 예외처리 추가 및 주석 추가

- src/main/java/com/sparta/doguin/domain/answer/controller/ApplyAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/BulletinAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/InquiryAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/NoticeAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/QuestionAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/service/ApplyAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/BulletinAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/InquiryAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/NoticeAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/QuestionAnswerService.java
- src/main/java/com/sparta/doguin/domain/common/response/ApiResponseAnswerEnum.java
> refact. 답변(Answer) 예외처리 추가 및 주석 추가

- src/main/java/com/sparta/doguin/domain/user/service/AuthService.java
- src/main/java/com/sparta/doguin/domain/user/service/UserService.java
fix. AuthUserService로직에 있던 findById를 UserService로 수정하였음
> fix. AuthUserService로직에 있던 findById를 UserService로 수정하였음

- src/main/java/com/sparta/doguin/domain/answer/controller/AnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/ApplyAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/BulletinAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/InquiryAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/NoticeAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/QuestionAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/entity/Answer.java
- src/main/java/com/sparta/doguin/domain/answer/repository/AnswerRepository.java
- src/main/java/com/sparta/doguin/domain/answer/service/AnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/ApplyAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/BulletinAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/InquiryAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/NoticeAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/QuestionAnswerService.java
> refact. 답변(Answer) 서비스 메서드 분리

- src/main/java/com/sparta/doguin/domain/question/entity/Question.java
> update. Question Entity 생성자 추가

- src/main/java/com/sparta/doguin/domain/question/repository/QuestionRepository.java
- src/main/java/com/sparta/doguin/domain/question/service/QuestionService.java
questionService에 findAllByUserId 메서드 추가
> update. questionService에 findAllByUserId 메서드 추가

- src/main/java/com/sparta/doguin/domain/question/entity/Question.java
> bugfix. question 연관관계 추가

- src/main/java/com/sparta/doguin/domain/follow/controller/FollowController.java
> refactor. FollowController

- build.gradle
- src/main/java/com/sparta/doguin/config/S3Config.java
- src/main/java/com/sparta/doguin/domain/attachment/constans/AttachmentTargetType.java
- src/main/java/com/sparta/doguin/domain/attachment/controller/AttachmentController.java
- src/main/java/com/sparta/doguin/domain/attachment/entity/Attachment.java
- src/main/java/com/sparta/doguin/domain/attachment/model/AttachmentResponse.java
- src/main/java/com/sparta/doguin/domain/attachment/repository/AttachmentRepository.java
- src/main/java/com/sparta/doguin/domain/attachment/service/component/PathService.java
- src/main/java/com/sparta/doguin/domain/attachment/service/impl/AttachmentDeleteServiceImpl.java
- src/main/java/com/sparta/doguin/domain/attachment/service/impl/AttachmentDownloadServiceImpl.java
- src/main/java/com/sparta/doguin/domain/attachment/service/impl/AttachmentGetServiceImpl.java
- src/main/java/com/sparta/doguin/domain/attachment/service/impl/AttachmentUpdateServiceImpl.java
- src/main/java/com/sparta/doguin/domain/attachment/service/impl/AttachmentUploadServiceImpl.java
- src/main/java/com/sparta/doguin/domain/attachment/service/interfaces/AttachmentDeleteService.java
- src/main/java/com/sparta/doguin/domain/attachment/service/interfaces/AttachmentDownloadService.java
- src/main/java/com/sparta/doguin/domain/attachment/service/interfaces/AttachmentGetService.java
- src/main/java/com/sparta/doguin/domain/attachment/service/interfaces/AttachmentUpdateService.java
- src/main/java/com/sparta/doguin/domain/attachment/service/interfaces/AttachmentUploadService.java
- src/main/java/com/sparta/doguin/domain/attachment/service/s3/S3Service.java
- src/main/java/com/sparta/doguin/domain/attachment/validate/AttachmentValidator.java
- src/main/java/com/sparta/doguin/domain/common/exception/FileException.java
- src/main/java/com/sparta/doguin/domain/common/globalpath/GlobalPath.java
- src/main/java/com/sparta/doguin/domain/common/response/ApiResponseFileEnum.java
- src/main/java/com/sparta/doguin/domain/portfolio/controller/PortfolioController.java
- src/main/java/com/sparta/doguin/domain/portfolio/model/PortfolioRequest.java
- src/main/java/com/sparta/doguin/domain/portfolio/model/PortfolioResponse.java
- src/main/java/com/sparta/doguin/domain/portfolio/service/PortfolioService.java
- src/main/java/com/sparta/doguin/domain/portfolio/service/PortfolioServiceImpl.java
- src/main/resources/application.yml
- src/test/java/com/sparta/doguin/domain/setup/DataUtil.java
1. 첨부 (여러개)
2. 다운로드 (여러개)
3. 수정 (여러개)
4. 삭제 (여러개)
5. 포트폴리오 API에서 파일들을 설정 할 수 있습니다
> feat. S3 파일 CRUD 기능 구현완료

- src/main/java/com/sparta/doguin/domain/answer/controller/ApplyAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/BulletinAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/EventAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/InquiryAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/NoticeAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/controller/QuestionAnswerController.java
- src/main/java/com/sparta/doguin/domain/answer/service/AnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/ApplyAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/BulletinAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/EventAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/InquiryAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/NoticeAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/QuestionAnswerService.java
- src/main/java/com/sparta/doguin/domain/question/controller/QuestionController.java
- src/main/java/com/sparta/doguin/domain/question/service/QuestionService.java
> bugfix. AuthUser import 경로 수정

- src/main/java/com/sparta/doguin/config/security/JwtSecurityFilter.java
- src/main/java/com/sparta/doguin/domain/attachment/constans/AttachmentTargetType.java
- src/main/java/com/sparta/doguin/domain/attachment/controller/AttachmentController.java
- src/main/java/com/sparta/doguin/domain/attachment/entity/Attachment.java
- src/main/java/com/sparta/doguin/domain/attachment/repository/AttachmentRepository.java
- src/main/java/com/sparta/doguin/domain/attachment/service/component/AttachmentUtil.java
- src/main/java/com/sparta/doguin/domain/attachment/service/component/PathService.java
- src/main/java/com/sparta/doguin/domain/attachment/service/constans/Extension.java
- src/main/java/com/sparta/doguin/domain/attachment/service/impl/AttachmentDeleteServiceImpl.java
- src/main/java/com/sparta/doguin/domain/attachment/service/impl/AttachmentDownloadServiceImpl.java
- src/main/java/com/sparta/doguin/domain/attachment/service/impl/AttachmentGetServiceImpl.java
- src/main/java/com/sparta/doguin/domain/attachment/service/impl/AttachmentUpdateServiceImpl.java
- src/main/java/com/sparta/doguin/domain/attachment/service/impl/AttachmentUploadServiceImpl.java
- src/main/java/com/sparta/doguin/domain/attachment/service/interfaces/AttachmentGetService.java
- src/main/java/com/sparta/doguin/domain/attachment/service/interfaces/AttachmentUpdateService.java
- src/main/java/com/sparta/doguin/domain/attachment/service/s3/S3Service.java
- src/main/java/com/sparta/doguin/domain/attachment/validate/AttachmentValidator.java
- src/main/java/com/sparta/doguin/domain/common/response/ApiResponseFileEnum.java
- src/main/java/com/sparta/doguin/domain/portfolio/service/PortfolioServiceImpl.java
- src/test/java/com/sparta/doguin/domain/portfolio/service/PortfolioServiceImplTest.java
- src/test/java/com/sparta/doguin/domain/query/QueryTest.java
- src/test/java/com/sparta/doguin/domain/setup/DataUtil.java
1. 이름 직관적으로 변경
2. S3와 DB와 서로 같은 트랜잭션으로 묶이게 변경 (DB에서 하나라도 실패하면 S3에서도 작업이 이루어지지않게 변경)
3. 코드 수정
4. 예외처리 추가 (사이즈 2mb보다 큰지, 확장자가 이미지인지)
> refactor. 전반적인 파일관련 수정

- src/main/java/com/sparta/doguin/domain/answer/service/QuestionAnswerService.java
- src/main/java/com/sparta/doguin/domain/question/entity/Question.java
- src/test/java/com/sparta/doguin/domain/answer/service/ApplyAnswerServiceTest.java
- src/test/java/com/sparta/doguin/domain/answer/service/QuestionAnswerServiceTest.java
- src/test/java/com/sparta/doguin/domain/question/service/QuestionServiceTest.java
- src/test/java/com/sparta/doguin/domain/setup/DataUtil.java
Q&A(Question, Answer, Apply) 서비스 로직 테스트 코드 작성
> test. Q&A(Question, Answer, Apply) 서비스 로직 테스트 코드 작성

- src/main/java/com/sparta/doguin/domain/answer/repository/AnswerRepository.java
- src/main/java/com/sparta/doguin/domain/answer/service/BulletinAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/EventAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/InquiryAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/NoticeAnswerService.java
- src/main/java/com/sparta/doguin/domain/common/response/ApiResponseAnswerEnum.java
> bugfix. 게시판(자유, 공지, 문의, 이벤트) 댓글 오류 수정

- src/main/java/com/sparta/doguin/domain/common/response/ApiResponseQuestionEnum.java
- src/main/java/com/sparta/doguin/domain/question/controller/QuestionController.java
- src/main/java/com/sparta/doguin/domain/question/dto/QuestionResponse.java
- src/main/java/com/sparta/doguin/domain/question/entity/Question.java
- src/main/java/com/sparta/doguin/domain/question/repository/QuestionRepository.java
- src/main/java/com/sparta/doguin/domain/question/repository/QuestionRepositoryQuery.java
- src/main/java/com/sparta/doguin/domain/question/repository/QuestionRepositoryQueryImpl.java
- src/main/java/com/sparta/doguin/domain/question/service/QuestionService.java
> feat. 질문 검색 기능 구현

- src/main/java/com/sparta/doguin/domain/answer/service/BulletinAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/EventAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/InquiryAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/NoticeAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/QuestionAnswerService.java
- src/main/java/com/sparta/doguin/domain/common/response/ApiResponseAnswerEnum.java
- src/test/java/com/sparta/doguin/domain/answer/service/ApplyAnswerServiceTest.java
- src/test/java/com/sparta/doguin/domain/answer/service/BulletinAnswerServiceTest.java
- src/test/java/com/sparta/doguin/domain/answer/service/EventAnswerServiceTest.java
- src/test/java/com/sparta/doguin/domain/answer/service/InquiryAnswerServiceTest.java
- src/test/java/com/sparta/doguin/domain/answer/service/NoticeAnswerServiceTest.java
- src/test/java/com/sparta/doguin/domain/answer/service/QuestionAnswerServiceTest.java
- src/test/java/com/sparta/doguin/domain/question/service/QuestionServiceTest.java
> test. 질문, 답변, 댓글 테스트 코드 수정

- src/main/java/com/sparta/doguin/config/SecurityConfig.java
- src/main/java/com/sparta/doguin/domain/common/response/ApiResponseQuestionEnum.java
- src/main/java/com/sparta/doguin/domain/question/controller/QuestionController.java
- src/main/java/com/sparta/doguin/domain/question/entity/Question.java
- src/main/java/com/sparta/doguin/domain/question/service/QuestionService.java
> feat. 질문 채택 기능 구현

- src/main/java/com/sparta/doguin/domain/discussions/controller/DiscussionController.java
- src/main/java/com/sparta/doguin/domain/discussions/service/DiscussionService.java
> fix. 토론게시판 북마크 기능 순환참조 문제 해결

- src/main/java/com/sparta/doguin/domain/question/controller/QuestionController.java
- src/main/java/com/sparta/doguin/domain/question/dto/QuestionRequest.java
- src/main/java/com/sparta/doguin/domain/question/dto/QuestionResponse.java
- src/main/java/com/sparta/doguin/domain/question/entity/Question.java
- src/main/java/com/sparta/doguin/domain/question/service/QuestionService.java
- src/test/java/com/sparta/doguin/domain/question/service/QuestionServiceTest.java
- src/test/java/com/sparta/doguin/domain/setup/DataUtil.java
> feat. 질문 이미지 첨부파일 기능 구현

- src/main/java/com/sparta/doguin/domain/answer/entity/Answer.java
- src/main/java/com/sparta/doguin/domain/answer/enums/AnswerStatus.java
- src/main/java/com/sparta/doguin/domain/answer/repository/AnswerRepository.java
- src/main/java/com/sparta/doguin/domain/answer/service/AnswerBatchService.java
- src/main/java/com/sparta/doguin/domain/answer/service/ApplyAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/BulletinAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/EventAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/InquiryAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/NoticeAnswerService.java
- src/main/java/com/sparta/doguin/domain/answer/service/QuestionAnswerService.java
- src/main/java/com/sparta/doguin/domain/question/service/QuestionService.java
- src/test/java/com/sparta/doguin/domain/question/service/QuestionServiceTest.java
> 댓글 삭제 기능 수정, 질문 테스트 코드 수정
